"""UI contract (port of Ui/IUi.cs) shared by the console and Textual implementations."""

from __future__ import annotations

import enum
from collections.abc import Awaitable, Callable
from typing import Protocol, runtime_checkable


class UiStyle(enum.Enum):
    NORMAL = "normal"
    USER = "user"
    TOOL = "tool"
    ERROR = "error"
    WARN = "warn"
    DIM = "dim"
    SUCCESS = "success"
    INFO = "info"
    ASSISTANT = "assistant"
    REASONING = "reasoning"
    ACCENT = "accent"


# Banner rows: each row is a list of (text, color-key) runs (see banner.render()).
BannerRows = list[list[tuple[str, str]]]


@runtime_checkable
class UI(Protocol):
    def banner(self, rows: BannerRows) -> None: ...
    def set_identity(self, name: str) -> None: ...
    def set_status(self, left: str, right: str) -> None: ...
    def set_working(self, working: bool) -> None: ...
    def begin_assistant(self) -> None: ...
    def append_inline(self, text: str) -> None: ...
    def append_line(self, text: str, style: UiStyle = UiStyle.NORMAL) -> None: ...
    def set_commands(self, names: list[str]) -> None: ...
    def start_spinner(self, label: str) -> None: ...
    def update_spinner(self, label: str) -> None: ...
    def stop_spinner(self) -> None: ...
    def clear(self) -> None: ...
    async def select(self, title: str, options: list[str]) -> int | None: ...
    async def edit_permissions(
        self, categories: list[tuple[str, str]], state: dict
    ) -> dict | None: ...
    async def run(
        self,
        on_submit: Callable[[str], Awaitable[None]],
        on_interrupt: Callable[[], Awaitable[None]] | None = None,
        on_start: Callable[[], Awaitable[None]] | None = None,
    ) -> None: ...
    def request_stop(self) -> None: ...
