"""Shared helpers for docs-structure tests.

These parse ``mkdocs.yml`` and ``docs/reference/scripts/commands.yml`` once
per test session and expose plain Python data structures (sets of relative
paths, flattened nav entries) so each test file stays a short list of
assertions.
"""

from __future__ import annotations

from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
MKDOCS_YML = REPO_ROOT / "mkdocs.yml"
COMMANDS_YML = DOCS_DIR / "reference" / "scripts" / "commands.yml"

# Historical-artifact filename prefixes that must never appear under docs/.
FORBIDDEN_PREFIXES = (
    "PLAN-",
    "SPEC-",
    "DESIGN-",
    "NEXT-",
    "TODO-",
    "AGENT-PROMPT-",
    "FOURPAGER-",
)

# Case-insensitive regex fragments that indicate agent-authorship or
# personal-review attribution rather than neutral repository voice.
FORBIDDEN_ATTRIBUTION_PATTERNS = (
    r"author:\s*(claude|codex|copilot|chatgpt|gpt|openai)",
    r"written by\s*(claude|codex|copilot|chatgpt|gpt|openai)",
    r"reviewed by\s*(claude|codex|copilot|chatgpt|gpt|openai)",
    r"^\s*openai\s*:",
    r"generated by\s*(claude|codex|copilot|chatgpt|gpt|openai)",
)


def load_mkdocs_config() -> dict:
    with MKDOCS_YML.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def flatten_nav(nav_entry) -> list[str]:
    """Flatten a MkDocs ``nav:`` structure into docs_dir-relative paths."""
    paths: list[str] = []
    if isinstance(nav_entry, str):
        paths.append(nav_entry)
    elif isinstance(nav_entry, dict):
        for value in nav_entry.values():
            paths.extend(flatten_nav(value))
    elif isinstance(nav_entry, list):
        for item in nav_entry:
            paths.extend(flatten_nav(item))
    return paths


def all_nav_paths() -> set[str]:
    config = load_mkdocs_config()
    paths: list[str] = []
    for entry in config.get("nav", []):
        paths.extend(flatten_nav(entry))
    return set(paths)


def all_public_markdown_files() -> set[str]:
    """Every ``*.md`` file under ``docs/``, relative to ``docs/``."""
    return {str(p.relative_to(DOCS_DIR)) for p in DOCS_DIR.rglob("*.md")}


def load_commands_manifest() -> list[dict]:
    if not COMMANDS_YML.exists():
        return []
    with COMMANDS_YML.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return data.get("commands", [])


def redirect_map() -> dict[str, str]:
    config = load_mkdocs_config()
    for plugin_entry in config.get("plugins", []):
        if isinstance(plugin_entry, dict) and "redirects" in plugin_entry:
            redirects_cfg = plugin_entry["redirects"] or {}
            return redirects_cfg.get("redirect_maps", {}) or {}
    return {}
